os: linux
dist: focal
language: shell
env:
  global:
    - BAR=bar
addons:
  apt:
    packages:
      - ca-certificates
install: skip
jobs:
  include:
    - name: "condition with regex"
      script: echo "condition with regex"
      if: env(BAR) =~ /^(?i)(bar|1).*/
    - name: "condition-without-regex"
      script: echo "condition without regex"
      if: env(BAR) =~ [ABC]
